import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { Container, createTheme, ThemeProvider } from "@mui/material";
import { defaultTheme } from "../styles/theme/defaultTheme";
import { Introduction } from "../components/Introduction";
import { Plataforma } from "../components/Plataforma";
import { Cadrastro } from "../components/Cadastro";
import Formulário from "../components/Formulário";
import { GroupChallenge } from "../components/GroupChallenge";

const Home: NextPage = () => {
  return (
    <Container sx={{ marginTop: "50px", maxWidth: "1000px" }}>
      <ThemeProvider theme={defaultTheme}>
        <Head>
          <title>Educação através da tecnologia</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <Introduction />
        <Cadrastro />
        <Plataforma />
        <GroupChallenge />
        <Formulário />
      </ThemeProvider>
    </Container>
  );
};

export default Home;
