import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import hero from "../assets/hero.svg";
import star from "../assets/star.svg";
import book from "../assets/book.svg";
import { Container } from "@mui/material";
import {
  ButtonStyled,
  Cadastro,
  Footer,
  Introduction,
  Plataforma,
} from "../styles/pages/Home";

const Home: NextPage = () => {
  return (
    <Container sx={{ marginTop: "100px", maxWidth: "1000px" }}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Introduction>
        <div className={"c-grid1"}>
          <h1>Dar acesso a educação atraves da tecnologia.</h1>
          <div className={"c-image-container"}>
            <Image
              src={hero}
              alt='Criança com roupa de formatura segurando uma maçã'
            />
          </div>
        </div>
        <ul className={"c-grid2"}>
          <li>
            <div>
              <Image src={book} alt='Livro' />
            </div>
            <h3>Incentivo ao estudo</h3>
            <hr />
            <p>
              Ao final de cada ano letivo os melhores alunos recebem presentes
              como notebooks ou celulares.
            </p>
          </li>
          <li>
            <div>
              <Image src={star} alt='Estrela' />
            </div>
            <h3>Utilizando gamificação como método de ensino principal.</h3>
            <hr />
            <p>
              Com desafios individuais e em grupo o aluno tem mais motivação e
              interesse em estudar.
            </p>
          </li>
          <li>
            <div>
              <Image src={book} alt='Livro' />
            </div>
            <h3>Criada pensando na acessibilidade.</h3>
            <hr />
            <p>
              A plataforma foi criada já pensada em atender alunos com
              necessidades especiais.
            </p>
          </li>
        </ul>
      </Introduction>
      <Cadastro>
        <div className={"c-text-grid"}>
          <hr />
          <h2>Cadastro</h2>
          <p>
            Temos dois processos para os cadastros. Primeiro sendo escolas já
            cadatradas em nosso sistema passam para nós, alunos que eles não
            consiguiram inserir dentro da escola, por motivos de não ter
            estrutura adequada para o acesso do aluno ou falta de vagas entre
            outros motivos. Segundo incrições indivuáis onde os pais passam a
            nos contatar e passando por todo um processo para podermos entender
            a sua situação.
            <br />
            <br />
            Para ambos os processos avaliamos a situação em que se encontra o
            aluno e caso precise ajudamos com o acesso a internet e dispositivos
            para o acesso a nossa plataforma.
          </p>
        </div>
        <div className={"c-image-grid"}></div>
      </Cadastro>
      <Plataforma>
        <div className={"c-text-grid"}>
          <hr />
          <h2>Plataforma de ensino</h2>
          <h4>Acessibilidade</h4>
          <p>
            Uma plataforma já pensada em acessibilidade para dar suporte aos
            alunos com necessidades especiais, tendo funcionalizades como
            <strong> sistema de voz</strong> para navegação e{" "}
            <strong> mudança de cores</strong>.
          </p>

          <h4>Gamificação</h4>
          <p>
            A nossa plataforma utiliza da gamificação como principal método de
            ensino, criando aulas dinâmicas e com maior participação do aluno,
            utilizando desafios individuáis e em grupo com recompensas entre a
            turma ajudando a desenvolver o trabalho em equipe.
          </p>
        </div>
        <div className={"c-image-grid"}></div>
      </Plataforma>
      <Footer>
        <h2>O seu comentário é bem-vindo</h2>
        <p>
          A nossa plataforma veio com o intuito de dar acesso a educação as
          pessoas em funerabilidade social, economica ou física, com esse
          pensamento acreditamos que sempre podemos melhorar e aceita-mos de
          braços abertos sugestões de melhoria ou locais que podemos dar mais
          atenção entre outros.
        </p>
        <div>
          <input placeholder='Ensira sua mensagem' type='text' />
          <ButtonStyled variant='contained'>Enviar</ButtonStyled>
        </div>
      </Footer>
    </Container>
  );
};

export default Home;
